services:

  backend:
    build: ./backend
    env_file:
      - ./backend/.env
    environment:
      S3_ENDPOINT_URL: http://localstack:4566
      REDIS_HOST: redis
    container_name: backend
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - localstack

  frontend:
    build: ./frontend
    container_name: frontend
    env_file:
      - ./frontend/.env
    ports:
      - "5173:5173"
    depends_on:
      - backend

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

  localstack:
    image: localstack/localstack:3.8
    container_name: localstack
    ports:
      - "4566:4566"
    environment:
      SERVICES: s3
      DEBUG: 1

  seed-s3:
    build: ./backend
    env_file:
      - ./backend/.env
    environment:
      S3_ENDPOINT_URL: http://localstack:4566
    depends_on:
      - localstack
    command: sh -c "sleep 15 && python -m scripts.seed_s3"
